#!/usr/bin/env bash
# build-index.sh — regenerate INDEX.md at the root of a hand-off store (output/handoffs/ or $HR_HANDOFF_ROOT) from the
# front matter of every companies/*/*/handoff.md.
#
#   bash build-index.sh [repo-root]      default: the current directory
#
# Reads only top-level `key: value` front-matter lines and the `stages:` list; writes INDEX.md.
set -euo pipefail

root="${1:-.}"
cd "$root"

if [ ! -d companies ]; then
  echo "build-index.sh: no companies/ directory under $(pwd) — is this the hand-off store root?" >&2
  exit 1
fi

# fm <file> <key> — the front-matter value for key, or "-" when absent / null
fm() {
  awk -v k="$2" '
    NR == 1 && $0 != "---" { exit }
    NR > 1 && $0 == "---"  { exit }
    NR > 1 {
      i = index($0, ":"); if (i == 0) next
      key = substr($0, 1, i - 1); gsub(/^[ \t]+|[ \t]+$/, "", key)
      if (key == k) {
        v = substr($0, i + 1); sub(/#.*$/, "", v)
        gsub(/^[ \t]+|[ \t]+$/, "", v); gsub(/^"|"$/, "", v)
        if (v == "" || v == "null") v = "-"
        print v; found = 1; exit
      }
    }
    END { if (!found) print "-" }' "$1"
}

# stage_line <file> — "done/total" from the stages list (skipped counts as done)
stage_line() {
  awk '
    /^stages:/            { inlist = 1; next }
    inlist && /^[^ \t-]/  { inlist = 0 }
    inlist && /name:/     {
      total++
      if ($0 ~ /status:[ \t]*(done|skipped)/) done++
    }
    END { if (total) printf "%d/%d\n", done, total; else print "-" }' "$1"
}

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

find companies -mindepth 3 -maxdepth 3 -name handoff.md -print0 | sort -z |
while IFS= read -r -d '' f; do
  printf '| %s | %s | %s | %s | %s | %s | %s | %s | [%s](%s) |\n' \
    "$(fm "$f" platform)" "$(fm "$f" company)" "$(fm "$f" domain)" \
    "$(stage_line "$f")" "$(fm "$f" final)" "$(fm "$f" updated)" \
    "$(fm "$f" developer)" "$(fm "$f" csm)" "$f" "$f"
done | sort -t '|' -k2,2 -k3,3 > "$tmp"

{
  echo "# Customer hand-offs — index"
  echo
  echo "Generated by \`scripts/build-index.sh\` on $(date +%Y-%m-%d). Do not edit by hand — edit the"
  echo "front matter of the hand-off documents and re-run the script."
  echo
  echo "| Platform | Company | Website | Stage | Final | Last updated | Developer | CSM | Document |"
  echo "|---|---|---|---|---|---|---|---|---|"
  cat "$tmp"
} > INDEX.md

echo "INDEX.md: $(wc -l < "$tmp" | tr -d ' ') website(s) indexed"
